export const BARF_FACTS = [
  "It's time to barf: a sidereal day clocks in at 23h 56m 4s.",
  "Solar noon drifts because Earth moves while it spins.",
  "Giordano Bruno argued for plural worlds and was burned in 1600.",
  "Hypatia taught mathematics and astronomy before a mob killed her in 415.",
  "Mercury sprints through an 88-day year and still looks tired.",
  "Venus rotates backward, as if it resents the schedule.",
  "The moon is inching away from Earth by about 3.8 centimeters a year.",
  "A leap second is humanity admitting the planet will not obey the clocks.",
  "Copernicus nudged Earth off the throne and philosophy never recovered.",
  "A barf bag is just a portable critique of angular momentum.",
  "Mars keeps time with sols, because even planets need branding.",
  "Precession makes the sky slowly rewrite the address of north.",
  "Aristarchus proposed a moving Earth long before Europe was ready for it.",
  "Jupiter's magnetic field could ruin your lunch from very far away.",
  "Sundials fail in clouds; the second hand never cares.",
  "Sidereal time follows the stars instead of the sun's daily bluff.",
  "Every orbit is a negotiation between falling and missing.",
  "Ptolemy stacked circles on circles and still had to squint.",
  "Kepler traded perfect circles for ellipses and the cosmos got sharper.",
  "Chronophobia is fear of time; this ride prefers practical demonstrations.",
]
